apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ipfs-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CircuitRelay is the Schema for the circuitrelays API
      displayName: Circuit Relay
      kind: CircuitRelay
      name: circuitrelays.cluster.ipfs.io
      version: v1alpha1
    - description: Ipfs is the Schema for the ipfs API
      displayName: Ipfs
      kind: Ipfs
      name: ipfs.cluster.ipfs.io
      version: v1alpha1
  description: Operator for IPFS clustering
  displayName: ipfs
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IPFS
  links:
  - name: Ipfs Operator
    url: https://ipfs-operator.domain
  maturity: alpha
  provider:
    name: redhat-et
  version: 0.0.0
